# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nietzsche/Downloads/snowman/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nietzsche/Downloads/snowman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nietzsche/Downloads/snowman/CMakeFiles /Users/nietzsche/Downloads/snowman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nietzsche/Downloads/snowman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nc-arch-arm

# Build rule for target.
nc-arch-arm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc-arch-arm
.PHONY : nc-arch-arm

# fast build rule for target.
nc-arch-arm/fast:
	$(MAKE) -f nc/arch/arm/CMakeFiles/nc-arch-arm.dir/build.make nc/arch/arm/CMakeFiles/nc-arch-arm.dir/build
.PHONY : nc-arch-arm/fast

#=============================================================================
# Target rules for targets named nc-arch-mips

# Build rule for target.
nc-arch-mips: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc-arch-mips
.PHONY : nc-arch-mips

# fast build rule for target.
nc-arch-mips/fast:
	$(MAKE) -f nc/arch/mips/CMakeFiles/nc-arch-mips.dir/build.make nc/arch/mips/CMakeFiles/nc-arch-mips.dir/build
.PHONY : nc-arch-mips/fast

#=============================================================================
# Target rules for targets named nc-arch-allegrex

# Build rule for target.
nc-arch-allegrex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc-arch-allegrex
.PHONY : nc-arch-allegrex

# fast build rule for target.
nc-arch-allegrex/fast:
	$(MAKE) -f nc/arch/allegrex/CMakeFiles/nc-arch-allegrex.dir/build.make nc/arch/allegrex/CMakeFiles/nc-arch-allegrex.dir/build
.PHONY : nc-arch-allegrex/fast

#=============================================================================
# Target rules for targets named nc-arch-x86

# Build rule for target.
nc-arch-x86: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc-arch-x86
.PHONY : nc-arch-x86

# fast build rule for target.
nc-arch-x86/fast:
	$(MAKE) -f nc/arch/x86/CMakeFiles/nc-arch-x86.dir/build.make nc/arch/x86/CMakeFiles/nc-arch-x86.dir/build
.PHONY : nc-arch-x86/fast

#=============================================================================
# Target rules for targets named nc-common

# Build rule for target.
nc-common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc-common
.PHONY : nc-common

# fast build rule for target.
nc-common/fast:
	$(MAKE) -f nc/common/CMakeFiles/nc-common.dir/build.make nc/common/CMakeFiles/nc-common.dir/build
.PHONY : nc-common/fast

#=============================================================================
# Target rules for targets named nc-core

# Build rule for target.
nc-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc-core
.PHONY : nc-core

# fast build rule for target.
nc-core/fast:
	$(MAKE) -f nc/core/CMakeFiles/nc-core.dir/build.make nc/core/CMakeFiles/nc-core.dir/build
.PHONY : nc-core/fast

#=============================================================================
# Target rules for targets named nc-gui

# Build rule for target.
nc-gui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc-gui
.PHONY : nc-gui

# fast build rule for target.
nc-gui/fast:
	$(MAKE) -f nc/gui/CMakeFiles/nc-gui.dir/build.make nc/gui/CMakeFiles/nc-gui.dir/build
.PHONY : nc-gui/fast

#=============================================================================
# Target rules for targets named nc-input-elf

# Build rule for target.
nc-input-elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc-input-elf
.PHONY : nc-input-elf

# fast build rule for target.
nc-input-elf/fast:
	$(MAKE) -f nc/input/elf/CMakeFiles/nc-input-elf.dir/build.make nc/input/elf/CMakeFiles/nc-input-elf.dir/build
.PHONY : nc-input-elf/fast

#=============================================================================
# Target rules for targets named nc-input-mach-o

# Build rule for target.
nc-input-mach-o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc-input-mach-o
.PHONY : nc-input-mach-o

# fast build rule for target.
nc-input-mach-o/fast:
	$(MAKE) -f nc/input/mach-o/CMakeFiles/nc-input-mach-o.dir/build.make nc/input/mach-o/CMakeFiles/nc-input-mach-o.dir/build
.PHONY : nc-input-mach-o/fast

#=============================================================================
# Target rules for targets named nc-input-pe

# Build rule for target.
nc-input-pe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc-input-pe
.PHONY : nc-input-pe

# fast build rule for target.
nc-input-pe/fast:
	$(MAKE) -f nc/input/pe/CMakeFiles/nc-input-pe.dir/build.make nc/input/pe/CMakeFiles/nc-input-pe.dir/build
.PHONY : nc-input-pe/fast

#=============================================================================
# Target rules for targets named nocode

# Build rule for target.
nocode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nocode
.PHONY : nocode

# fast build rule for target.
nocode/fast:
	$(MAKE) -f nocode/CMakeFiles/nocode.dir/build.make nocode/CMakeFiles/nocode.dir/build
.PHONY : nocode/fast

#=============================================================================
# Target rules for targets named snowman

# Build rule for target.
snowman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snowman
.PHONY : snowman

# fast build rule for target.
snowman/fast:
	$(MAKE) -f snowman/CMakeFiles/snowman.dir/build.make snowman/CMakeFiles/snowman.dir/build
.PHONY : snowman/fast

#=============================================================================
# Target rules for targets named capstone-static

# Build rule for target.
capstone-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capstone-static
.PHONY : capstone-static

# fast build rule for target.
capstone-static/fast:
	$(MAKE) -f 3rd-party/capstone/capstone/CMakeFiles/capstone-static.dir/build.make 3rd-party/capstone/capstone/CMakeFiles/capstone-static.dir/build
.PHONY : capstone-static/fast

#=============================================================================
# Target rules for targets named udis86

# Build rule for target.
udis86: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udis86
.PHONY : udis86

# fast build rule for target.
udis86/fast:
	$(MAKE) -f 3rd-party/libudis86/CMakeFiles/udis86.dir/build.make 3rd-party/libudis86/CMakeFiles/udis86.dir/build
.PHONY : udis86/fast

#=============================================================================
# Target rules for targets named iberty

# Build rule for target.
iberty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iberty
.PHONY : iberty

# fast build rule for target.
iberty/fast:
	$(MAKE) -f 3rd-party/libiberty/CMakeFiles/iberty.dir/build.make 3rd-party/libiberty/CMakeFiles/iberty.dir/build
.PHONY : iberty/fast

#=============================================================================
# Target rules for targets named undname

# Build rule for target.
undname: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 undname
.PHONY : undname

# fast build rule for target.
undname/fast:
	$(MAKE) -f 3rd-party/undname/CMakeFiles/undname.dir/build.make 3rd-party/undname/CMakeFiles/undname.dir/build
.PHONY : undname/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/strip"
	@echo "... nc-arch-arm"
	@echo "... nc-arch-mips"
	@echo "... nc-arch-allegrex"
	@echo "... nc-arch-x86"
	@echo "... nc-common"
	@echo "... nc-core"
	@echo "... nc-gui"
	@echo "... nc-input-elf"
	@echo "... nc-input-mach-o"
	@echo "... nc-input-pe"
	@echo "... nocode"
	@echo "... snowman"
	@echo "... capstone-static"
	@echo "... udis86"
	@echo "... iberty"
	@echo "... undname"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

